//! ```rust
//!         Parser::new(StrSource::new(input.as_ref()));
//!         parser.load(&mut event_listener, true)?;
//!
//!         match event_listener.docs.into_iter().next() {
//!             Some(document) => Ok(document),
//!             None => Err(YamlError::new("No document found in the YAML input")),
//!         }
//!     }
//! }
//! ```
//!
//! ### Module `spanned_node`
//! This module contains the implementation of a YAML loader capable of processing YAML input and converting it into structured document nodes using the `SpannedEventReceiver` trait.
//!
//! ---
//!
//! ### Struct `YamlLoader`
//!
//! A YAML loader that processes events generated by a parser and builds a hierarchy of YAML documents as `Node` objects.
//!
//! #### Generics
//! - `'input`: Lifetime tied to the input YAML being processed.
//! - `Node`: A type that implements the `LoadableYamlNode` trait to represent the parsed YAML document nodes.
//!
//! #### Fields
//! - `docs`: A vector storing the parsed YAML documents.
//! - `doc_stack`: A stack for managing the current document hierarchy during parsing.
//! - `key_stack`: A stack of keys used in mapping operations within YAML.
//! - `marker`: Phantom data to associate the struct with the input lifetime.
//! - `anchor_map`: A mapping between anchor IDs and their corresponding `Node` objects.
//!
//! ---
//!
//! #### Trait Implementations
//!
//! ##### `Default`
//! Provides a default constructor that initializes the `YamlLoader` with empty stacks and containers.
//!
//! ##### `SpannedEventReceiver`
//! Processes parsed YAML events and updates the internal document structure accordingly. Implements the core logic for handling YAML constructs such as sequences, mappings, scalars, and anchors.
//!
//! - `on_event`: Handles individual YAML parsing events and updates the document stack, key stack, and other internal state.
//!
//! ---
//!
//! #### Methods
//!
//! ##### `into_documents`
//! Converts the `YamlLoader` into a `Vec<Node>` representing the parsed YAML documents.
//!
//! - Returns:
//!   - A vector of YAML documents as `Node` objects.
//!
//! ---
//!
//! ##### `insert_new_node`
//! Helper function to insert a new node into the appropriate position within the current document structure. Handles anchors, tags, and node types.
//!
//! - Arguments:
//!   - `node`: The new `Node` to insert.
//!   - `anchor_id`: The anchor ID associated with the node, if any.
//!   - `tag`: An optional tag describing the type or schema of the node.
//!
//! ---
//!
//! ##### `insert_collection`
//! Finalizes and inserts a collection node (sequence or mapping) into the document structure.
//!
//! - Arguments:
//!   - `marker`: Marker indicating the end of the collection in the source YAML.
//!
//! ---
//!
//! ##### `load_from_parser`
//! Parses a sequence of YAML documents from a provided parser instance.
//!
//! - Type Parameters:
//!   - `I`: A type implementing the `Source` trait for input handling.
//! - Arguments:
//!   - `parser`: A mutable reference to the `Parser` instance.
//! - Returns:
//!   - `Ok(Vec<Node>)`: A vector of parsed YAML documents.
//!   - `Err(YamlError)`: An error if parsing fails.
//!
//! ---
//!
//! ##### `load_from`
//! Parses YAML input from a string and returns a vector of parsed YAML documents.
//!
//! - Type Parameters:
//!   - `S`: A type implementing `AsRef<str>`.
//! - Arguments:
//!   - `input`: A YAML input source as a string.
//! - Returns:
//!   - `Ok(Vec<Node>)`: A vector of parsed YAML documents.
//!   - `Err(YamlError)`: An error if parsing fails.
//!
//! ---
//!
//! ##### `load_single`
//! Parses YAML input from a string and returns a single YAML document node.
//!
//! - Type Parameters:
//!   - `S`: A type implementing `AsRef<str>`.
//! - Arguments:
//!   - `input`: A YAML input source as a string.
//! - Returns:
//!   - `Ok(Node)`: The first parsed YAML document.
//!   - `Err(YamlError)`: An error if parsing fails or no documents are found.
//!
//! ---
//!
//! ### Example Usage
//!
//! ```rust
//! use crate::yam_core::{Parser, YamlLoader};
//! use yam_common::YamlDoc;
//!
//! let yaml_input = r#"
//! - name: Alice
//!   age: 28
//! - name: Bob
//!   age: 34
//! "#;
//!
//! let docs = YamlLoader::<YamlDoc>::load_from(yaml_input).unwrap();
//! for doc in docs {
//!     println!("{:?}", doc);
//! }
//! ```
//!
//! ---
//!
//! This documentation provides an overview of the `YamlLoader` functionality, detailed descriptions of its methods, and example usage scenarios for loading and parsing YAML input into structured nodes.
pub mod spanned_node;

use crate::Parser;
use crate::saphyr_tokenizer::{Event, Source, StrSource};
use crate::saphyr_tokenizer::{ScalarValue, SpannedEventReceiver};
use alloc::borrow::Cow;
use alloc::collections::BTreeMap;
use alloc::vec::Vec;
use core::marker::PhantomData;
use yam_common::loader::LoadableYamlNode;
use yam_common::{Marker, Span, Tag, YamlDoc, YamlEntry, YamlError};

pub struct YamlLoader<'input, Node>
where
    Node: LoadableYamlNode<'input>,
{
    docs: Vec<Node>,
    doc_stack: Vec<(Node, usize, Option<Cow<'input, Tag>>)>,
    key_stack: Vec<Node>,
    marker: PhantomData<&'input ()>,
    anchor_map: BTreeMap<usize, Node>,
}

impl<'i, Node> Default for YamlLoader<'i, Node>
where
    Node: LoadableYamlNode<'i>,
{
    fn default() -> Self {
        Self {
            docs: Vec::new(),
            doc_stack: Vec::new(),
            key_stack: Vec::new(),
            anchor_map: BTreeMap::new(),
            marker: PhantomData,
        }
    }
}

impl<'input, Node> SpannedEventReceiver<'input> for YamlLoader<'input, Node>
where
    Node: LoadableYamlNode<'input>,
{
    fn on_event(&mut self, ev: Event<'input>, span: Span) {
        let marker = span.start;
        match ev {
            Event::DocumentStart(_) | Event::Nothing | Event::StreamStart | Event::StreamEnd => {}
            #[cfg(feature = "comments")]
            Event::Comment(_) => {}
            Event::DocumentEnd => match self.doc_stack.pop() {
                Some((doc, ..)) => self.docs.push(doc),
                None => self.docs.push(Node::bad(span)),
            },
            Event::SequenceStart(aid, tag) => {
                self.doc_stack.push((
                    Node::from_bare_yaml(YamlDoc::Sequence(Vec::new())).with_start(marker),
                    aid,
                    tag,
                ));
            }
            Event::MappingStart(aid, tag) => {
                self.doc_stack.push((
                    Node::from_bare_yaml(YamlDoc::Mapping(Vec::new())).with_start(marker),
                    aid,
                    tag,
                ));
                self.key_stack.push(Node::bad(span));
            }
            Event::MappingEnd => {
                self.key_stack.pop();
                self.insert_collection(marker);
            }
            Event::SequenceEnd => {
                self.insert_collection(marker);
            }
            Event::Scalar(ScalarValue {
                value,
                anchor_id,
                tag,
                scalar_type,
            }) => {
                let node =
                    Node::from_bare_yaml(YamlDoc::from_cow_and_tag(value, scalar_type, &tag));
                self.insert_new_node(node, anchor_id, tag);
            }
            Event::Alias(anchor_id) => {
                let node = match self.anchor_map.get(&anchor_id) {
                    Some(n) => n.clone(),
                    None => Node::bad(span),
                };
                self.insert_new_node(node, anchor_id, None);
            }
        }
    }
}

impl<'input, Node> YamlLoader<'input, Node>
where
    Node: LoadableYamlNode<'input>,
{
    #[must_use]
    pub fn into_documents(self) -> Vec<Node> {
        self.docs
    }

    pub(crate) fn insert_new_node(
        &mut self,
        mut node: Node,
        anchor_id: usize,
        tag: Option<Cow<'input, Tag>>,
    ) {
        if anchor_id > 0 {
            self.anchor_map.insert(anchor_id, node.clone());
        }
        if let Some((parent_node, _, _)) = self.doc_stack.last_mut() {
            if let Some(tag) = tag
                && node.is_collection()
                && !tag.is_yaml_core_schema()
            {
                node = node.into_tagged(tag);
            }
            if parent_node.is_sequence() {
                parent_node.sequence_mut().push(node);
            } else if parent_node.is_mapping() {
                let curr_key = self.key_stack.last_mut().unwrap();

                if curr_key.is_bad_value() {
                    *curr_key = node;
                } else {
                    parent_node
                        .mapping_mut()
                        .push(YamlEntry::new(curr_key.take(), node));
                }
            }
        } else {
            self.doc_stack.push((node, anchor_id, tag));
        }
    }

    fn insert_collection(&mut self, marker: Marker) {
        if let Some((mut node, anchor_id, tag)) = self.doc_stack.pop() {
            node = node.with_end(marker);
            if let Some(tag) = tag
                && !tag.is_yaml_core_schema()
            {
                node = node.into_tagged(tag);
            }
            self.insert_new_node(node, anchor_id, None);
        }
    }

    ///
    /// Loads a sequence of YAML documents from a parser instance and returns them as a vector of `Node`s.
    ///
    /// # Type Parameters
    /// - `I`: A type that implements the `Source` trait, representing the source input for the parser.
    ///
    /// # Arguments
    /// - `parser`: A mutable reference to a `Parser` instance that processes the YAML input.
    ///
    /// # Returns
    /// - `Ok(Vec<Node>)`: A vector of `Node` objects representing the parsed YAML documents.
    /// - `Err(YamlError)`: An error if the parsing process fails.
    ///
    /// # Errors
    /// This function will return a `YamlError` if the parser encounters issues while parsing and processing input.
    ///
    /// # Example
    /// ```rust
    /// use crate::yam_core::{Parser, YamlLoader};
    /// use yam_common::YamlDoc;
    ///
    /// let mut parser = Parser::new_from_str("a: b");
    ///
    /// match YamlLoader::<YamlDoc>::load_from_parser(&mut parser) {
    ///     Ok(documents) => {
    ///         for node in documents {
    ///             println!("{:?}", node);
    ///         }
    ///     }
    ///     Err(e) => {
    ///         eprintln!("Failed to parse YAML: {}", e);
    ///     }
    /// }
    /// ```
    pub fn load_from_parser<I: Source>(
        parser: &mut Parser<'input, I>,
    ) -> Result<Vec<Node>, YamlError> {
        let mut loader = YamlLoader::default();
        parser.load(&mut loader, true)?;
        Ok(loader.into_documents())
    }

    ///
    /// Parses the given YAML input string and loads it into a `Vec<Node>`.
    ///
    /// # Type Parameters
    /// - `S`: A type that can be referenced as a string slice, implementing the `AsRef<str>` trait.
    ///
    /// # Arguments
    /// - `input`: A YAML input source, provided as a type that can be referenced as a string.
    ///
    /// # Returns
    /// - `Ok(Vec<Node>)`: A vector of `Node` objects representing the YAML documents parsed from the input.
    /// - `Err(YamlError)`: An error if the parsing process fails.
    ///
    /// # Errors
    /// Returns a `YamlError` if:
    /// - The input contains invalid YAML syntax.
    /// - Parsing fails due to other reasons, such as malformed structures in the YAML document.
    ///
    /// # Example
    /// ```rust
    /// use crate::yam_core::{Parser, YamlLoader};
    /// use yam_common::YamlDoc;
    ///
    /// let yaml_input = r#"
    /// - name: John
    ///   age: 30
    /// - name: Jane
    ///   age: 25
    /// "#;
    ///
    /// let result = YamlLoader::<YamlDoc>::load_from(&yaml_input);
    /// match result {
    ///     Ok(nodes) => {
    ///         for node in nodes {
    ///             println!("{:?}", node);
    ///         }
    ///     }
    ///     Err(err) => eprintln!("Failed to parse YAML: {}", err),
    /// }
    /// ```
    pub fn load_from<S: AsRef<str>>(input: S) -> Result<Vec<Node>, YamlError> {
        let mut event_listener = YamlLoader::default();
        let mut parser = Parser::new(StrSource::new(input.as_ref()));
        parser.load(&mut event_listener, true)?;
        Ok(event_listener.docs)
    }

    ///
    /// Loads a single YAML document from the given input string.
    ///
    /// # Type Parameters
    /// - `S`: A type that can be converted into a string slice (`&str`)
    ///   using the `AsRef<str>` trait, typically `String` or `&str`.
    ///
    /// # Parameters
    /// - `input`: The YAML input as a string-like object. This is the source from
    ///   which the function attempts to parse a single YAML document.
    ///
    /// # Returns
    /// - `Ok(Node)`: On success, returns the first YAML document (`Node`) parsed from the input string.
    /// - `Err(YamlError)`: Returns an error if:
    ///   - The input is invalid or cannot be parsed due to syntax or structural issues.
    ///   - No YAML document is found within the input (`YamlError::NoDocument`).
    ///
    /// # Errors
    /// - `YamlError::NoDocument`: Returned if no valid YAML documents are found in the input.
    /// - Any other error encountered during parsing, as propagated from the parser.
    ///
    /// # Example
    /// ```
    /// use crate::yam_core::{Parser, YamlLoader};
    /// use yam_common::YamlDoc;
    ///
    /// let yaml_input = r#"
    /// key: value
    /// array:
    ///   - item1
    ///   - item2
    /// "#;
    ///
    /// match YamlLoader::<YamlDoc>::load_single(&yaml_input) {
    ///     Ok(node) => println!("Parsed Node: {:?}", node),
    ///     Err(e) => eprintln!("Error loading YAML: {}", e),
    /// }
    /// ```
    ///
    /// # Notes
    /// This function expects only a single YAML document in the input. Any additional
    /// documents beyond the first will be ignored.
    ///
    pub fn load_single<S: AsRef<str>>(input: S) -> Result<Node, YamlError> {
        let mut event_listener = YamlLoader::default();
        let mut parser = Parser::new(StrSource::new(input.as_ref()));
        parser.load(&mut event_listener, false)?;
        event_listener
            .docs
            .first()
            .cloned()
            .ok_or(YamlError::NoDocument)
    }

    ///
    /// Parses a single YAML document from the given input source and returns it as a `Node`.
    ///
    /// # Type Parameters
    /// - `I`: A type that implements the `Source` trait, representing the input data source.
    ///
    /// # Arguments
    /// - `parser`: The input source containing the [Parser] that parses the input.
    ///
    /// # Returns
    /// - `Ok(Node)`: The parsed YAML document represented as a `Node` if successful.
    /// - `Err(YamlError)`: An error if no document is found in the input or if parsing fails.
    ///
    /// # Errors
    /// - `YamlError::NoDocument`: Returned if there is no document available in the parsed input.
    /// - Other variants of `YamlError`: Returned if there is an issue during parsing.
    ///
    /// # Example
    /// ```
    /// use crate::yam_core::{Parser, YamlLoader};
    /// use yam_common::YamlDoc;
    ///
    /// let yaml_input = r#"
    /// key: value
    /// array:
    ///   - item1
    ///   - item2
    /// "#;
    /// let mut parser = Parser::new_from_str(&yaml_input);
    /// match YamlLoader::<YamlDoc>::load_single_from_parser(&mut parser) {
    ///     Ok(node) => println!("Parsed Node: {:?}", node),
    ///     Err(e) => eprintln!("Error loading YAML: {}", e),
    /// }
    /// ```
    /// # Notes
    /// This function expects only a single YAML document in the input. Any additional
    /// documents beyond the first will be ignored.
    ///
    pub fn load_single_from_parser<I: Source>(
        parser: &mut Parser<'input, I>,
    ) -> Result<Node, YamlError> {
        let mut event_listener = YamlLoader::default();
        parser.load(&mut event_listener, false)?;
        event_listener
            .docs
            .first()
            .cloned()
            .ok_or(YamlError::NoDocument)
    }

    ///
    /// Loads a single YAML document from the given input source.
    ///
    /// This function takes an input source that implements the `Source` trait
    /// and attempts to parse it into a single YAML document. If parsing succeeds,
    /// it returns a `Node` representing the document. If no document is found or
    /// the parsing fails, an appropriate error is returned.
    ///
    /// # Type Parameters
    /// - `I`: A type that implements the `Source` trait, representing the input source.
    ///
    /// # Arguments
    /// - `input`: An input source that provides the YAML content to be loaded.
    ///
    /// # Returns
    /// - `Ok(Node)`: The first parsed YAML document as a `Node`.
    /// - `Err(YamlError)`: An error if no document is found or parsing fails. Possible errors include:
    ///   - `YamlError::NoDocument`: No valid YAML document was found in the input.
    ///   - Other `YamlError` variants describing parsing issues.
    ///
    /// # Errors
    /// This function will return an error in any of the following cases:
    /// - The input source does not contain a valid YAML document.
    /// - Parsing fails due to syntactical issues in the YAML content.
    ///
    /// # Example
    /// ```rust
    /// use yam_common::{YamlDoc};
    /// use yam_core::saphyr_tokenizer::StrSource;
    /// use yam_core::YamlLoader;
    ///
    /// let input = StrSource::new("---\nkey: value\n");
    /// match YamlLoader::<YamlDoc>::load_single_source(input) {
    ///     Ok(node) => println!("Successfully loaded: {:?}", node),
    ///     Err(e) => eprintln!("Failed to load YAML: {:?}", e),
    /// }
    /// ```
    ///
    /// # Note
    /// The function only extracts the first document if the input source contains multiple YAML documents.
    /// If you need to handle multiple documents, consider using appropriate methods.
    ///
    pub fn load_single_source<I: Source>(input: I) -> Result<Node, YamlError> {
        let mut event_listener = YamlLoader::default();
        let mut parser = Parser::new(input);
        parser.load(&mut event_listener, false)?;
        event_listener
            .docs
            .first()
            .cloned()
            .ok_or(YamlError::NoDocument)
    }
}
